name: Delete_Submodules

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      submodule_path:
        description: 'Submodule path to delete'
        type: string
        required: false
        default: ''
      all:
        description: 'Delete all repos'
        type: boolean
        required: true
        default: true

jobs:
  delete_submodules:
    runs-on: ubuntu-latest
    steps:
      - name: delete-submodules
        uses: gendloop/delete-submodules@v1.0.0
        with:
          submodule_path: ${{ inputs.submodule_path }}
          all: ${{ inputs.all }}
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
