name: Generate_Readme_For_Repos

permissions:
  contents: write
  actions: write

on:
  workflow_run:
    workflows:
      - Get_Repos_By_Topics
    types:
      - completed
  workflow_dispatch:

jobs:
  generate_readme_for_repos:
    runs-on: ubuntu-latest
    steps:
      - name: generate-readme-for-repos
        uses: gendloop/generate-readme-for-repos@v1.0.1
        with:
          label: 'App'
